### ISSUE TITLE
Handle content-directories other than 'wp-content'

### ISSUE THREAD

**Issue by goldfoot** [short-pixel-optimizer/shortpixel-image-optimiser#79] opened 2021-02-12 16:46 UTC
Running plugin version 4.21.1 / Wordpress 5.6.1 on Apache and PHP 7.4.

This concerns the automatic delivery of webp-files in the frontend. My settings:

- Create WebP images
- Deliver the WebP versions of the images in the front-end: Using the `<PICTURE>` tag syntax
- Global (processes the whole output buffer before sending the HTML to the browser)

The issue:
If a content directory other than `wp-content` is set, the WebP-files will not be delivered. If the constant `WP_CONTENT_DIR` is set to a directory other than `wp-content`, e.g. via `define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/content' );` , then the absolute path of the WebP-file is not generated correctly.

Example:
Original file at `https://mydomain.com/content/uploads/image.jpg` (absolute path: 'var/www/content/uploads/image.jpg')
Return path: `var/www/content/content/uploads/image.wepb` (note the extra `/content`).

The corresponding file: [class/Controller/FileSystemController.php](https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/blob/v4.21.1/class/Controller/FileSystemController.php#L131):

`$wpContentAbs = str_replace( 'wp-content', '', WP_CONTENT_DIR);`

Only `wp-content` gets replaced, hence the duplicate in the absolute path. This results in a failing `file_exists` and the `<IMG>` tag not being replaced.

In my case, I changed the following to meet make it work:

```diff
--- a/class/Controller/FileSystemController.php
+++ b/class/Controller/FileSystemController.php
@@ -128,7 +128,7 @@ Class FileSystemController extends \ShortPixel\Controller
     */
     public function getWPAbsPath()
     {
-        $wpContentAbs = str_replace( 'wp-content', '', WP_CONTENT_DIR);
+        $wpContentAbs = str_replace( array('wp-content', 'content'), '', WP_CONTENT_DIR);
         if (ABSPATH == $wpContentAbs)
           $abspath = ABSPATH;
         else
```

**Important:** This is not a universal solution as it does not consider any other custom content directories except `wp-content` and `content`.

**Comment by bschuiling** [comment] 2021-02-16 10:08
Hi, 

This is a good point, thanks for bringing it up.  

At the moment I can't think of any other good solution to get the base content location from a URL .  WordPress doesn't really provide any function for this sadly.   I'll put it on the list to think of a more dynamic solution . 

However there is a filter for this path in the same function: 

  $abspath = apply_filters('shortpixel/filesystem/abspath', $abspath );

You can use that to return the base path where the content is located ( e.g. /var/www/ ) via a snippet.

**Comment by goldfoot** [comment] 2021-02-16 17:01
Maybe a dynamic solution is to compare the paths in `WP_CONENT_DIR` and the result of `get_home_path()`. Something like this:

```php
$contentPath = WP_CONTENT_DIR;
$homePath = get_home_path(); // returns the root directory of the Wordpress installation
$contentDir = str_replace($homePath, '', $contentPath);
$wpContentAbs = str_replace( $contentDir, '', WP_CONTENT_DIR);
```

But this is just from the top of my head.

**Comment by bschuiling** [comment] 2021-02-16 17:40
-) The problem is that the home_path returns the root of the WordPress *installation* . This is not the directory where the content is, at least doesn't need to be. 

-) If somebody has already configured WP_CONTENT_DIR, it's mostly sure they are running from some other path. 

A config like: 
/var/www/app/[wordpress] 
/disk2/www/content/[images] 

wouldn't work. 

-) Also home_path defaults to ABPATH if it get's confused. 

These are issues the whole class is trying to solve :) . Thanks for thinking with us though,  maybe this check might party help to fix things.

**Comment by matt08** [comment] 2021-10-14 11:02
I have the same issue and only hardcode path without my "media" custom folder at the end  helps me:
`$abspath = '/home/aaa/domains/domain.tld/public_html/dev/'`

when the media is on `/home/aaa/domains/domain.tld/public_html/dev/` (domain.tld/dev/media/)

**Comment by pdobrescu** [comment] 2023-08-31 16:59
dear @goldfoot and @matt08,

I know it's been years since you opened this issue, but I hope we managed to get it resolved with this version:

https://shortpixel.com/downloads/shortpixel-image-optimiser-5.4.1-DEV03.zip

can you please check it and let me know if it now works as expected?

Many thanks for your patience!

**Comment by matt08** [comment] 2023-09-02 11:36
Finally!
Updated from 4.22.6 (with my path modification). Works perfectly for me. 
Problem solved @pdobrescu  :)

**Comment by pdobrescu** [comment] 2023-09-04 06:28
Awesome, that's great news @matt08, thanks a lot for the confirmation! We'll soon release version 5.4.1 😉

**Closed** 2023-09-04 19:54 UTC
