### ISSUE TITLE
Uncaught Error: Class 'ShortPixelMeta' not found

### ISSUE THREAD

**Issue by jakebellacera** [short-pixel-optimizer/shortpixel-image-optimiser#65] opened 2020-07-29 17:52 UTC
Getting this error when updating to `4.19.3` on Pantheon (previous versions worked just fine):

```
Uncaught Error: Class 'ShortPixelMeta' not found in /code/wp-content/plugins/shortpixel-image-optimiser/class/wp-short-pixel.php:47
Stack trace:
#0 /code/wp-content/plugins/shortpixel-image-optimiser/shortpixel-plugin.php(57): WPShortPixel->__construct()
#1 /code/wp-includes/class-wp-hook.php(287): ShortPixel\ShortPixelPlugin->lowInit('')
#2 /code/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /code/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /code/wp-settings.php(403): do_action('plugins_loaded')
#5 /code/wp-config.php(205): require_once('/code/wp-settin...')
#6 /code/wp-load.php(37): require_once('/code/wp-config...')
#7 /code/wp-admin/admin.php(34): require_once('/code/wp-load.p...')
#8 /code/wp-admin/index.php(10): require_once('/code/wp-admin/...')
#9 {main} thrown in /code/wp-content/plugins/shortpixel-image-optimiser/class/wp-short-pixel.php on line 47
```

I had to manually deactivate the plugin. Once I did that, I attempted to reactivate it and this error appeared:

```
Fatal error: Uncaught Error: Class 'ShortPixel\Model\EnvironmentModel' not found in /code/wp-content/plugins/shortpixel-image-optimiser/shortpixel-plugin.php:98 Stack trace:
#0 /code/wp-content/plugins/shortpixel-image-optimiser/shortpixel-plugin.php(396): ShortPixel\ShortPixelPlugin->env()
#1 /code/wp-content/plugins/shortpixel-image-optimiser/shortpixel-plugin.php(363): ShortPixel\ShortPixelPlugin::deactivatePlugin()
#2 /code/wp-includes/class-wp-hook.php(287): ShortPixel\ShortPixelPlugin::activatePlugin('')
#3 /code/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#4 /code/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /code/wp-admin/plugins.php(179): do_action('activate_shortp...')
#6 {main} thrown in /code/wp-content/plugins/shortpixel-image-optimiser/shortpixel-plugin.php on line 98
```

Thoughts?

**Comment by pdobrescu** [comment] 2020-07-29 18:02
hi @jakebellacera and thanks for bringing this to our attention. Can you please tell us if you have the site code versioned on a Git repo on Pantheon? Can you also check if you have the https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/blob/master/class/plugin.json file inside the `class` folder of the plugin?

Thanks!

**Comment by jakebellacera** [comment] 2020-07-29 18:15
@pdobrescu yes we do use Git on Pantheon, and the `plugin.json` file does exist within the `class` folder of the plugin. Here are the contents:

```json
{"name":"ShortPixel\/Plugin","description":"ShortPixel AutoLoader","type":"function","autoload":{"psr-4":{"ShortPixel":"class"},"files":["shortpixel_api.php","class\/wp-short-pixel.php","class\/wp-shortpixel-settings.php","class\/view\/shortpixel_view.php","class\/shortpixel-png2jpg.php","class\/front\/img-to-picture-webp.php","class\/Model\/shortpixel-entity.php","class\/Model\/shortpixel-meta.php","class\/Model\/shortpixel-folder.php","class\/db\/shortpixel-db.php","class\/db\/wp-shortpixel-db.php","class\/db\/shortpixel-custom-meta-dao.php","class\/db\/wp-shortpixel-media-library-adapter.php","class\/db\/shortpixel-meta-facade.php","class\/external\/cloudflare.php","class\/external\/flywheel.php","class\/external\/gravityforms.php","class\/external\/helpscout.php","class\/external\/nextgen.php","class\/external\/securi.php","class\/external\/shortpixel_queue_db.php","class\/external\/visualcomposer.php","class\/external\/wp-offload-media.php","class\/external\/wpengine.php"]}}
```

**Comment by pdobrescu** [comment] 2020-08-03 11:54
uderstood, the file seems to be ok @jakebellacera. In order to investigate this further, can you please send us a zip archive with the whole plugin to help@shortpixel.com, mentioning this issue? And it would also be helpful to have your main `.gitignore` file, to check if there's something there that could ignore some of our plugin files. thanks!

**Comment by pdobrescu** [comment] 2023-05-06 13:58
hey @jakebellacera, I'm following up on this: do you still face this issue on Pantheon, or it has been resolved? Thanks

**Comment by pdobrescu** [comment] 2023-09-19 13:30
After testing the latest version on Pantheon, we cannot reproduce this issue, closing it.

**Closed by pdobrescu** 2023-09-19 13:30 UTC
